-- CreateTable
CREATE TABLE "USUARIOS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "matricula" INTEGER NOT NULL,
    "senha" TEXT NOT NULL,
    "cargo" TEXT NOT NULL,
    "pontos" INTEGER NOT NULL DEFAULT 0,
    "role" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MODULOS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "MODULOS_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CONTEUDOS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "modulo_id" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL,
    "titulo" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "ordem" INTEGER NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "CONTEUDOS_modulo_id_fkey" FOREIGN KEY ("modulo_id") REFERENCES "MODULOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CONTEUDOS_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TRILHAS_APRENDIZAGEM" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "TRILHAS_APRENDIZAGEM_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TRILHA_MODULOS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "trilha_id" INTEGER NOT NULL,
    "conteudo_id" INTEGER NOT NULL,
    "ordem" INTEGER NOT NULL,
    CONSTRAINT "TRILHA_MODULOS_trilha_id_fkey" FOREIGN KEY ("trilha_id") REFERENCES "TRILHAS_APRENDIZAGEM" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TRILHA_MODULOS_conteudo_id_fkey" FOREIGN KEY ("conteudo_id") REFERENCES "MODULOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CONTEUDO_CHECK" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "conteudo_id" INTEGER NOT NULL,
    "data_assistido" DATETIME NOT NULL,
    CONSTRAINT "CONTEUDO_CHECK_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CONTEUDO_CHECK_conteudo_id_fkey" FOREIGN KEY ("conteudo_id") REFERENCES "CONTEUDOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "QUIZ" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "modulo_id" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "QUIZ_modulo_id_fkey" FOREIGN KEY ("modulo_id") REFERENCES "MODULOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "QUIZ_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "QUESTOES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "quiz_id" INTEGER NOT NULL,
    "texto" TEXT NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "QUESTOES_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "QUIZ" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "QUESTOES_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ALTERNATIVAS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "questao_id" INTEGER NOT NULL,
    "texto" TEXT NOT NULL,
    "correta" BOOLEAN NOT NULL,
    CONSTRAINT "ALTERNATIVAS_questao_id_fkey" FOREIGN KEY ("questao_id") REFERENCES "QUESTOES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "QUIZ_RESPOSTAS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "questao_id" INTEGER NOT NULL,
    "alternativa_id" INTEGER NOT NULL,
    "data_resposta" DATETIME NOT NULL,
    CONSTRAINT "QUIZ_RESPOSTAS_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "QUIZ_RESPOSTAS_questao_id_fkey" FOREIGN KEY ("questao_id") REFERENCES "QUESTOES" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "QUIZ_RESPOSTAS_alternativa_id_fkey" FOREIGN KEY ("alternativa_id") REFERENCES "ALTERNATIVAS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PONTUACAO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "tipo_evento" TEXT NOT NULL,
    "referencia_id" INTEGER NOT NULL,
    "pontos" INTEGER NOT NULL,
    "data_evento" DATETIME NOT NULL,
    "descricao" TEXT,
    CONSTRAINT "PONTUACAO_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOEDAS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "tipo_evento" TEXT NOT NULL,
    "referencia_id" INTEGER NOT NULL,
    "moedas" INTEGER NOT NULL,
    "data_evento" DATETIME NOT NULL,
    "descricao" TEXT,
    CONSTRAINT "MOEDAS_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TROFEUS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "tipo_evento" TEXT NOT NULL,
    "quantidade_minima" INTEGER NOT NULL,
    "peso" INTEGER NOT NULL,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "TROFEUS_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "USUARIO_TROFEUS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "trofeu_id" INTEGER NOT NULL,
    "data_aquisicao" DATETIME NOT NULL,
    CONSTRAINT "USUARIO_TROFEUS_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "USUARIO_TROFEUS_trofeu_id_fkey" FOREIGN KEY ("trofeu_id") REFERENCES "TROFEUS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CERTIFICADOS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "trilha_id" INTEGER NOT NULL,
    "url_certificado" TEXT NOT NULL,
    "data_emissao" DATETIME NOT NULL,
    CONSTRAINT "CERTIFICADOS_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CERTIFICADOS_trilha_id_fkey" FOREIGN KEY ("trilha_id") REFERENCES "TRILHAS_APRENDIZAGEM" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "RECOMPENSAS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "moedas_requeridas" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL,
    "quantidade_disponivel" INTEGER,
    "gestor_id" INTEGER NOT NULL,
    CONSTRAINT "RECOMPENSAS_gestor_id_fkey" FOREIGN KEY ("gestor_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "USUARIO_RECOMPENSAS" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "recompensa_id" INTEGER NOT NULL,
    "data_resgate" DATETIME NOT NULL,
    "status" TEXT NOT NULL,
    CONSTRAINT "USUARIO_RECOMPENSAS_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "USUARIO_RECOMPENSAS_recompensa_id_fkey" FOREIGN KEY ("recompensa_id") REFERENCES "RECOMPENSAS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TRILHA_PROGRESO_USUARIO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "usuario_id" INTEGER NOT NULL,
    "trilha_id" INTEGER NOT NULL,
    "percentual" REAL NOT NULL,
    "finalizado" BOOLEAN NOT NULL,
    "data_inicio" DATETIME NOT NULL,
    "data_finalizacao" DATETIME,
    CONSTRAINT "TRILHA_PROGRESO_USUARIO_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TRILHA_PROGRESO_USUARIO_trilha_id_fkey" FOREIGN KEY ("trilha_id") REFERENCES "TRILHAS_APRENDIZAGEM" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_matricula_key" ON "USUARIOS"("matricula");
